FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /workspace

RUN useradd --create-home --uid 1000 --shell /usr/sbin/nologin learner \
    && chown -R learner:learner /workspace

USER learner
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_NOLOGO=1

CMD ["dotnet", "--version"]
