"""add curriculum graph and learning state, drop self report mastery

Revision ID: 4227e015bd46
Revises: f6a7b8c9d0e1
Create Date: 2026-09-15 09:58:51.436015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4227e015bd46'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostic_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('research_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mastery_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('requires_concept_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'requires_concept_id', name='uq_concept_dependency')
    )
    op.create_table('concept_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('locked', 'available', 'introduced', 'researching', 'discussing', 'attempted', 'testing', 'blocked', 'diagnosis', 'knowledge_gap', 'explained', 'needs_review', 'verification', 'verified', 'mastered', name='concept_status', native_enum=False), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('diagnostic_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_explanation', sa.Text(), nullable=False),
    sa.Column('verified_via_skip', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_project_id', 'concept_id', name='uq_concept_state')
    )
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_id', sa.Integer(), nullable=False),
    sa.Column('blocked_concept_id', sa.String(length=100), nullable=False),
    sa.Column('suspected_concept_id', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='knowledge_gap_status', native_enum=False), nullable=False),
    sa.Column('diagnostic_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blocked_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suspected_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_defenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_id', sa.Integer(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.Enum('pending', 'needs_work', 'passed', name='project_defense_verdict', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_project_id', name='uq_project_defense_user_project')
    )
    op.create_table('research_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learner_notes', sa.Text(), nullable=False),
    sa.Column('learner_summary', sa.Text(), nullable=False),
    sa.Column('remaining_questions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('original_response_ref', sa.Text(), nullable=False),
    sa.Column('learner_response', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'skipped', name='retrieval_check_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'concept_id', name='uq_milestone_concept')
    )
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_milestone_id', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_milestone_id'], ['user_milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_milestone_id', name='uq_reflection_user_milestone')
    )
    op.drop_table('learner_knowledge')
    op.drop_table('card_checkpoints')
    op.drop_table('learner_states')
    op.drop_table('roadmap_items')
    op.drop_table('concept_cards')
    op.alter_column('milestone_reviews', 'verdict',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('needs_work', 'awaiting_understanding', 'passed', name='milestone_review_verdict', native_enum=False),
               existing_nullable=False)
    op.add_column(
        'projects',
        sa.Column(
            'curriculum_mode',
            sa.Enum('deterministic', 'ai_generated', name='project_curriculum_mode', native_enum=False),
            nullable=False,
            server_default='ai_generated',
        ),
    )
    op.alter_column('projects', 'curriculum_mode', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'curriculum_mode')
    op.alter_column('milestone_reviews', 'verdict',
               existing_type=sa.Enum('needs_work', 'awaiting_understanding', 'passed', name='milestone_review_verdict', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.create_table('concept_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('why_it_matters', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('research_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('checkpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('concept_cards_milestone_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], name=op.f('concept_cards_user_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('concept_cards_pkey')),
    sa.UniqueConstraint('user_project_id', 'milestone_id', 'name', name=op.f('uq_concept_card'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('roadmap_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concept_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('teaching', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('roadmap_items_milestone_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], name=op.f('roadmap_items_user_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_items_pkey')),
    sa.UniqueConstraint('user_project_id', 'milestone_id', 'concept_name', name=op.f('uq_roadmap_item'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('learner_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('researched_concepts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('can_explain', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('can_reproduce', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('help_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('question_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('build_step_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('learner_states_milestone_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], name=op.f('learner_states_user_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_states_pkey')),
    sa.UniqueConstraint('user_project_id', 'milestone_id', name=op.f('uq_learner_state_milestone'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('card_checkpoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['concept_cards.id'], name=op.f('card_checkpoints_card_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('card_checkpoints_pkey'))
    )
    op.create_table('learner_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concept_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mastery', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('attempted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('researched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('failed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], name=op.f('learner_knowledge_user_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_knowledge_pkey')),
    sa.UniqueConstraint('user_project_id', 'concept_name', name=op.f('uq_learner_knowledge_concept'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('reflections')
    op.drop_table('milestone_concepts')
    op.drop_table('retrieval_checks')
    op.drop_table('research_records')
    op.drop_table('project_defenses')
    op.drop_table('knowledge_gaps')
    op.drop_table('concept_states')
    op.drop_table('concept_dependencies')
    op.drop_table('concepts')
    # ### end Alembic commands ###
